---
# Ansible playbook for OpenShift files transfer
- name: Transfer openshift files to local machine 
  hosts: all
  remote_user: ec2-user
  become: true
  become_method: sudo
  tasks: 

  - name: Create openshift directory
    file:
      path: openshift
      state: directory

  - name: Fetch openshift install config file
    ansible.builtin.copy:
      src: files/install-config.yaml
      dest: /home/ec2-user/openshift/install-config.yaml
      
# Mirror is public repo for openshift install files
# Recommend to check URL to ensure latest install file is stated

  - name: Download OpenShift install for Linux from repo
    get_url:
      url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux-4.11.17.tar.gz
      dest: /home/ec2-user/openshift
